INSERT INTO Players (name) VALUES ('Jannik Sinner');
INSERT INTO Players (name) VALUES ('Carlos Alcaraz');
INSERT INTO Players (name) VALUES ('Alexander Zverev');
INSERT INTO Players (name) VALUES ('Novak Djokovic');
INSERT INTO Players (name) VALUES ('Daniil Medvedev');
INSERT INTO Players (name) VALUES ('Taylor Fritz');
INSERT INTO Players (name) VALUES ('Iga Swiatek');
INSERT INTO Players (name) VALUES ('Aryna Sabalenka');
INSERT INTO Players (name) VALUES ('Jessica Pegula');
INSERT INTO Players (name) VALUES ('Elena Rybakina');
INSERT INTO Players (name) VALUES ('Jasmine Paolini');

INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (1, 5, 1);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (2, 3, 3);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (10, 7, 7);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (8, 4, 4);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (10, 11, 11);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (3, 5, 5);

INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (8, 4, 4);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (1, 11, 11);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (3, 7, 5);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (6, 2, 2);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (10, 11, 11);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (4, 5, 5);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (1, 2, 1);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (2, 3, 2);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (3, 5, 5);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (9, 4, 4);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (10, 4, 10);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (7, 1, 1);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (4, 6, 6);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (8, 9, 8);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (2, 5, 5);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (8, 4, 4);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (10, 11, 10);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (9, 7, 9);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (8, 1, 8);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (1, 7, 7);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (3, 9, 9);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (4, 1, 1);
INSERT INTO Matches(first_player_id, second_player_id, winner_id) VALUES (2, 11, 2);
